# -*- coding: utf-8 -*-
"""Proyecto Visión Artificial - Detección de equipo de seguridad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDeqbQpgQQReVZ1PE_YqOK88oRsHzr--
"""

!pip install ultralytics

from ultralytics import YOLO

# 1. Cargamos el modelo base nano (ligero y rápido)
model = YOLO('yolov8n.pt')

# 2. Ejecutamos el entrenamiento
# Nota: Si subiste data.yaml directamente a la raíz de Colab, la ruta es 'data.yaml'
results = model.train(data='data.yaml', epochs=30, imgsz=640)

from google.colab import drive
drive.mount('/content/drive')

